### PR TITLE
Layout changes

### PR DESCRIPTION
**Pull request by pypingou**
These commits are just doing some indentation cleaning and space/tab mix correction

### CODE REVIEW

**Comment by pypingou** [comment]
This PR has been opened for 5 years now. It waited almost 2 years for someone to comment on it and nothing since.

I can rebase it once more, but only if there is interest in this change, otherwise I think we should just close that PR.

**Comment by kjetilk** [comment]
Please rebase, I'll merge it.

The main problem is that we do not have a trigger to update the namespace document, so it will not show. Can we fix that, @ewilderj ?

**Comment by pypingou** [comment]
Rebased, but I realized I just undid the first commit of this PR (ie: the file is consistently using tabs in its latest version). So let me which you prefer (tabs or spaces) and I'll either drop the first commit, or fix the later one

**Comment by kjetilk** [comment]
Actually, my opinions aren't terribly strong on that. :-) I generally prefer tabs, lets see if anybody comes up with stronger opinions soon.

**Comment by ewilderj** [comment]
Yeah, let's stay with tabs for the sake of historical consistency.

Yes, need to put aside some time to make the auto-publish work. @kjetilk do you see any problem with keeping the schema be synchronized with `ewilderj:master` ?

**Comment by kjetilk** [comment]
OK, sounds good! So, @pypingou please drop the first commit. 

@ewilderj syncing with your master sounds good to me, it is the simplest thing that could possibly work :-)

**Comment by ewilderj** [comment]
great, I've blocked time on Friday to deal with this.

**Comment by pypingou** [comment]
Updated :)

**Pull request merged**
